### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This library will improve performance and greatly reduce memory allocations through object pooling of SemaphoreSlim objects.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@pipoburgos ?

**Comment by MarkCiliaVincenti** [comment]
@pipoburgos @pipoburgosdev ?

**Comment by pipoburgos** [comment]
Dear Mark,

I wanted to let you know that I have just seen your pull request, and I appreciate your efforts to make changes to the project. I will be reviewing the changes over the course of this week, and I will provide feedback as soon as possible.

Thank you for your contribution!

Best regards,
pipoburgos

**Comment by pipoburgos** [comment]
https://github.com/pipoburgos/SharedKernel/commit/ed7ed5bec1dd7a7e89967012de451b91b698a71b

**Pull request closed without merging**
