### PR TITLE
Bump AsyncKeyedLock to 6.3.0 and using new AsyncNonKeyedLocker

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@pipoburgos

**Comment by pipoburgos** [comment]
Changes incorporated in version 8.0.0.5

**Comment by MarkCiliaVincenti** [comment]
> Changes incorporated in version 8.0.0.5

You missed some changes actually @pipoburgos 

Compare
https://github.com/pipoburgos/SharedKernel/blob/master/src/Infrastructure/Caching/DistributedCacheHelper.cs
to
https://github.com/MarkCiliaVincenti/SharedKernel/blob/AsyncKeyedLockUpdate/src/Infrastructure/Caching/DistributedCacheHelper.cs

**Comment by MarkCiliaVincenti** [comment]
Also is there some reason why the SetAsync and GetOrCreateAsync<T> parameters there accept a parameter timeSpan but never use it?

**Comment by pipoburgos** [comment]
I have integrated the changes into the infrastructure layer. I have not imported your library since I want to have minimal dependencies with external libraries in that package. By the way, thank you very much @MarkCiliaVincenti for detecting the cache expiration bug.

**Comment by MarkCiliaVincenti** [comment]
> I have integrated the changes into the infrastructure layer. I have not imported your library since I want to have minimal dependencies with external libraries in that package. By the way, thank you very much @MarkCiliaVincenti for detecting the cache expiration bug.

But the change is still in the infrastructure layer and no additional dependency was needed to achieve this.

**Comment by pipoburgos** [comment]
I have used inversion of control so that any implementation can be used for the mutex manager.

**Comment by MarkCiliaVincenti** [comment]
> I have used inversion of control so that any implementation can be used for the mutex manager.

Ah OK, now I see the MutexManager which does something similar-ish to AsyncNonKeyedLocker. The code in DistributedCacheHelper wasn't using that before though.

**Comment by MarkCiliaVincenti** [comment]
@pipoburgos version 6.3.4 has been released which will give some 25% better performance when using pooled locking.

**Pull request closed without merging**
